# Generated by Django 5.0.13 on 2025-04-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diemdanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoigiandiemdanh', models.DateTimeField()),
                ('trangthai', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'DIEMDANH',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Giaovien',
            fields=[
                ('magiaovien', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hoten', models.CharField(max_length=100)),
                ('gioitinh', models.CharField(max_length=3)),
                ('ngaysinh', models.DateField(blank=True, null=True)),
                ('sdt', models.CharField(max_length=10, unique=True)),
                ('matkhau', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('quyen', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'GIAOVIEN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('makhoa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tenkhoa', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'KHOA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lop',
            fields=[
                ('malop', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tenlop', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'LOP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Monhoc',
            fields=[
                ('mamon', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tenmon', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'MONHOC',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nganh',
            fields=[
                ('manganh', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tennganh', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'NGANH',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sinhvien',
            fields=[
                ('masinhvien', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('hoten', models.CharField(max_length=100)),
                ('gioitinh', models.CharField(max_length=3)),
                ('ngaysinh', models.DateField()),
                ('sdt', models.CharField(max_length=10, unique=True)),
                ('ngaydangky', models.DateTimeField()),
                ('matkhau', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('quyen', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'SINHVIEN',
                'managed': False,
            },
        ),
    ]
