CREATE DATABASE FACE;
GO
USE FACE;

CREATE TABLE KHOA(
    MAKHOA VARCHAR(10) PRIMARY KEY,
    TENKHOA NVARCHAR(100) NOT NULL
);

CREATE TABLE NGANH(
    MANGANH VARCHAR(10) PRIMARY KEY,
    TENNGANH NVARCHAR(100) NOT NULL,
    MAKHOA VARCHAR(10) NOT NULL,
    FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
);

CREATE TABLE LOP(
    MALOP VARCHAR(10) PRIMARY KEY,
    TENLOP NVARCHAR(100) NOT NULL,
    MANGANH VARCHAR(10) NOT NULL,
    FOREIGN KEY (MANGANH) REFERENCES NGANH(MANGANH)
);

CREATE TABLE SINHVIEN (
    MASINHVIEN VARCHAR(11) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    GIOITINH NVARCHAR(3) CHECK (GIOITINH IN (N'Nam', N'Nữ')) NOT NULL,
    NGAYSINH DATE NOT NULL,
    SDT VARCHAR(10) UNIQUE CHECK (SDT LIKE '[0-9][0-9][0-9[0-9][0-9][0-9][0-9][0-9][0-9][0-9]') NOT NULL,
    NGAYDANGKY DATETIME DEFAULT GETDATE() NOT NULL,
    MATKHAU VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE CHECK (EMAIL LIKE '%@ctuet.edu.vn') NOT NULL,
    QUYEN VARCHAR(100) CHECK (QUYEN = 'Guest') NOT NULL,
    MANGANH VARCHAR(10) NOT NULL,
    MALOP VARCHAR(10) NOT NULL,
	MAKHOA VARCHAR(10) NOT NULL,
    FOREIGN KEY (MANGANH) REFERENCES NGANH(MANGANH),
	FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA),
    FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
);

CREATE TABLE GIAOVIEN(
    MAGIAOVIEN VARCHAR(10) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    GIOITINH NVARCHAR(3) CHECK (GIOITINH IN (N'Nam', N'Nữ')) NOT NULL,
    NGAYSINH DATE,
    SDT VARCHAR(10) UNIQUE CHECK (SDT LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') NOT NULL,
    MATKHAU VARCHAR(64) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE CHECK (EMAIL LIKE '%@edu.vn') NOT NULL,
    QUYEN VARCHAR(100) CHECK (QUYEN IN ('User', 'Admin')) NOT NULL,
    MAKHOA VARCHAR(10) NOT NULL,
    FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
);

CREATE TABLE MONHOC(
    MAMON VARCHAR(10) PRIMARY KEY,
    TENMON NVARCHAR(100) NOT NULL,
    MAKHOA VARCHAR(10) NOT NULL,
    MAGIAOVIEN VARCHAR(10) NOT NULL,
    FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA),
    FOREIGN KEY (MAGIAOVIEN) REFERENCES GIAOVIEN(MAGIAOVIEN)
);

CREATE TABLE DIEMDANH(
    MASINHVIEN VARCHAR(11) NOT NULL,
    THOIGIANDIEMDANH DATETIME DEFAULT GETDATE() NOT NULL,
    TRANGTHAI NVARCHAR(100) CHECK (TRANGTHAI IN (N'Có mặt', N'Vắng mặt')) NOT NULL,
    MAMON VARCHAR(10) NOT NULL,
    MAGIAOVIEN VARCHAR(10) NOT NULL,
    MALOP VARCHAR(10) NOT NULL
    PRIMARY KEY (MASINHVIEN, MAMON, MAGIAOVIEN, MALOP),
    FOREIGN KEY (MASINHVIEN) REFERENCES SINHVIEN(MASINHVIEN),
    FOREIGN KEY (MAMON) REFERENCES MONHOC(MAMON),
    FOREIGN KEY (MALOP) REFERENCES LOP(MALOP),
    FOREIGN KEY (MAGIAOVIEN) REFERENCES GIAOVIEN(MAGIAOVIEN)
);
